# Nome da aplicação
spring.application.name=sb-kafka-consumer

# Porta web do Consumer (Diferente para não dar conflito)
server.port=8081

# Conexão com o mesmo Kafka do Docker
spring.kafka.bootstrap-servers=localhost:9092

# A mesma propriedade do tópico para ele saber de onde ler
topicos.pagamento.request.topic=pagamento.request.topico.v1

