# Nome da aplicação
spring.application.name=sb-kafka-producer

# Porta web do Producer
server.port=8080

# Conexão com o Kafka do Docker
spring.kafka.bootstrap-servers=localhost:9092

# Propriedade customizada criada pelo instrutor (Traduzida para Properties)
topicos.pagamento.request.topic=pagamento.request.topico.v1
